#!/usr/bin/env python3
"""Convert Sonic deploy reference CSVs to a browser-friendly motion JSON.

Expected input directory layout (as generated by gear_sonic_deploy):
    input_dir/
        joint_pos.csv
        joint_vel.csv
        body_pos.csv
        body_quat.csv
        body_lin_vel.csv
        body_ang_vel.csv
        metadata.txt (optional)

Output JSON fields:
    fps: int
    duration: float
    joint_names: list[str]
    times: list[float]
    qpos: list[list[float]]  # [n, 7 + n_dofs]
    qvel: list[list[float]]  # [n, 6 + n_dofs]
    root_pos: list[list[float]]
    root_quat: list[list[float]]  # MuJoCo convention [w, x, y, z]
"""

import argparse
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd


G1_29DOF_JOINT_NAMES = [
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
    "waist_yaw_joint",
    "waist_roll_joint",
    "waist_pitch_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_roll_joint",
    "right_wrist_pitch_joint",
    "right_wrist_yaw_joint",
]


def _read_csv(path: Path) -> np.ndarray:
    return pd.read_csv(path).to_numpy(dtype=np.float32)


def convert(input_dir: Path, output_path: Path, fps: int = 30) -> None:
    input_dir = Path(input_dir)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    joint_pos = _read_csv(input_dir / "joint_pos.csv")  # [T, 29]
    joint_vel = _read_csv(input_dir / "joint_vel.csv")  # [T, 29]
    body_pos = _read_csv(input_dir / "body_pos.csv")    # [T, 14*3]
    body_quat = _read_csv(input_dir / "body_quat.csv")  # [T, 14*4]
    body_lin_vel = _read_csv(input_dir / "body_lin_vel.csv")
    body_ang_vel = _read_csv(input_dir / "body_ang_vel.csv")

    n_frames = joint_pos.shape[0]
    assert joint_vel.shape[0] == n_frames
    assert body_pos.shape[0] == n_frames
    assert body_quat.shape[0] == n_frames

    # Root is body_0 in the deploy CSVs (pelvis).
    root_pos = body_pos[:, 0:3]
    root_quat = body_quat[:, 0:4]  # [w, x, y, z]
    root_lin_vel = body_lin_vel[:, 0:3]
    root_ang_vel = body_ang_vel[:, 0:3]

    times = (np.arange(n_frames, dtype=np.float32) / fps).tolist()

    qpos = []
    qvel = []
    for t in range(n_frames):
        qpos.append(np.concatenate([root_pos[t], root_quat[t], joint_pos[t]]).tolist())
        qvel.append(np.concatenate([root_lin_vel[t], root_ang_vel[t], joint_vel[t]]).tolist())

    motion = {
        "fps": fps,
        "duration": round(n_frames / fps, 4),
        "joint_names": G1_29DOF_JOINT_NAMES,
        "times": times,
        "qpos": qpos,
        "qvel": qvel,
        "root_pos": root_pos.tolist(),
        "root_quat": root_quat.tolist(),
    }

    with open(output_path, "w") as f:
        json.dump(motion, f)

    print(f"Wrote {n_frames} frames ({motion['duration']:.2f}s @ {fps}Hz) to {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert Sonic deploy CSV reference to web motion JSON")
    parser.add_argument("input_dir", type=Path, help="Directory containing reference CSVs")
    parser.add_argument("output_path", type=Path, help="Output JSON path")
    parser.add_argument("--fps", type=int, default=30, help="Playback frames per second")
    args = parser.parse_args()
    convert(args.input_dir, args.output_path, args.fps)


if __name__ == "__main__":
    main()
